### ISSUE TITLE
We can't download full ebook

### ISSUE THREAD

**Issue by varta2014** [lorenzodifuccia/safaribooks#146] opened 2019-10-22 16:24 UTC
hi 
all script work normal
but when i check book is not complet full ?
example:
before i see number image 400... but now is 10 just few image download ?

>  Downloading book contents... (44 chapters)  **i think this normal**
Downloading book images... (5 files) **i think this bug need fix, image not just 5 ?**

and full book download in epub is just 48 page not complete 520 pages (this example)
and we see page in book not complete also with 3 points... 
https://i1.imageban.ru/out/2019/10/23/d1aea4d7e69679b7f56440b76c0ea56b.png

please fix bug
thank you

**Comment by Spectrum369** [comment] 2019-10-22 17:04
The same happens to me :(

**Comment by McPatate** [comment] 2019-10-23 09:41
Bump

**Comment by jnoob** [comment] 2019-10-24 01:24
Is it a permission restriciton oreilly add to its api?

**Comment by hassanaboueldahab** [comment] 2019-10-24 14:25
the same here

**Comment by izuolan** [comment] 2019-10-25 07:43
There are some problems existing login, I see a solution.

https://github.com/zqlu/safaribooks/tree/feat-oauth

Another related project (Node.js):

https://github.com/nicohaenggi/SafariBooks-Downloader

**Comment by varta2014** [comment] 2019-10-25 07:49
yes maybe problem login

**Comment by claudiuschan** [comment] 2019-10-25 14:05
same here. each page only show partial only.

**Comment by johnnybus** [comment] 2019-10-26 08:16
same here

**Comment by vjykrthk** [comment] 2019-10-27 15:07
I am also having the same issue

**Comment by ImMaury** [comment] 2019-10-27 23:42
Same here.

**Comment by McPatate** [comment] 2019-10-28 07:51
Hello @lorenzodifuccia , I have noticed that the problem comes from the way you parse the html received from the O'Reilly API (all you need to know is here : https://learning.oreilly.com/api/v1/book/<book-id>/chapter/ - you can try with : 9781491927274).

I have tried to debug your code, but after a few hours I decided to start from scratch. I have successfully implemented logging (thanks to your code) and I am moving on to parsing the html very soon.

Would you be interested to collaborate ? If so, I can make my repo public. Also, do you mind me using your code as documentation for the logging in part ?

**Comment by McPatate** [comment] 2019-10-28 09:36
Also, O'Reilly is currently out due to fires in California.

**Comment by tscangussu** [comment] 2019-10-28 12:11
> There are some problems existing login, I see a solution.
> 
> https://github.com/zqlu/safaribooks/tree/feat-oauth
> 
> Another related project (Node.js):
> 
> https://github.com/nicohaenggi/SafariBooks-Downloader

This code https://github.com/zqlu/safaribooks/tree/feat-oauth solved the problem for me.
I'm already using it and downloading books.

**Comment by obar1** [comment] 2019-10-29 21:40
ex of not complete https://learning.oreilly.com/library/view/driving-technical-change/9781680500011/
![image](https://user-images.githubusercontent.com/387386/67811453-1c1d4300-fa9d-11e9-9ecb-7cf69f6dc0a8.png)

**Comment by vikdean** [comment] 2019-10-31 12:20
I can confirm, books are downloading only partially.

**Comment by AsimShakour** [comment] 2019-11-01 18:22
Yes having same issue for me too for things aren't there and replaced with elipses

**Comment by mukuntharajaa** [comment] 2019-11-04 13:09
> Hello @lorenzodifuccia , I have noticed that the problem comes from the way you parse the html received from the O'Reilly API (all you need to know is here : https://learning.oreilly.com/api/v1/book/book-id/chapter/ - you can try with : 9781491927274).
> 
> I have tried to debug your code, but after a few hours I decided to start from scratch. I have successfully implemented logging (thanks to your code) and I am moving on to parsing the html very soon.
> 
> Would you be interested to collaborate ? If so, I can make my repo public. Also, do you mind me using your code as documentation for the logging in part ?

Do you have any patch to fix this ?

**Comment by vavdoshka** [comment] 2019-11-04 14:06
https://github.com/nicohaenggi/SafariBooks-Downloader
+ fix https://github.com/nicohaenggi/SafariBooks-Downloader/issues/68#issuecomment-524679093

worked for me

**Comment by McPatate** [comment] 2019-11-04 14:46
> https://github.com/nicohaenggi/SafariBooks-Downloader + fix [nicohaenggi/SafariBooks-Downloader#68 (comment)](https://github.com/nicohaenggi/SafariBooks-Downloader/issues/68#issuecomment-524679093)
> 
> worked for me

Doesn't work for all books, tried with "https://learning.oreilly.com/library/view/concrete-mathematics-a/9780134389974/" and it got all weird.

Here's the link to my repo : https://github.com/McPatate/orly_book_extractor

It isn't functionnal yet, but I am working on it ;)

**Comment by elrob** [comment] 2019-11-11 10:12
The above PR fixes this issue for me

**Comment by McPatate** [comment] 2019-11-11 17:57
Hey guys, my code is starting to work. I am still having problems with style and I am working on fixing links in the book.
This means that as of today, I am getting the full book and its images !

Any help would be welcome, here is the link for the repo (sic) : https://github.com/McPatate/orly_book_extractor

**Comment by varta2014** [comment] 2019-11-11 18:31
> Hey guys, my code is starting to work. I am still having problems with style and I am working on fixing links in the book.
> This means that as of today, I am getting the full book and its images !
> 
> Any help would be welcome, here is the link for the repo (sic) : https://github.com/McPatate/orly_book_extractor

thank you we hope you fix it and make it good like True EPUB format

**Comment by McPatate** [comment] 2019-11-13 21:39
Thank you @elrob. Definitely fixed it this time :D

**Comment by McPatate** [comment] 2019-11-15 16:57
@lorenzodifuccia have you gotten a chance to look into the problem?

**Comment by varta2014** [comment] 2019-11-15 17:01
**McPatate**  also your code not work :(
we need fix this bug

**Comment by elrob** [comment] 2019-11-18 03:16
For anyone still having issues:
I have investigated further and made some more changes that resolve another couple of issues with login.
Can you try again with a fresh version of this: https://github.com/elrob/safaribooks
Make sure to delete anything in the `Books` directory before trying.

**Comment by lorenzodifuccia** [comment] 2019-11-19 22:49
Closing and moving to #150

**Closed by lorenzodifuccia** 2019-11-19 22:49 UTC
Labels: Need more information, bug, help wanted
