### ISSUE TITLE
Every chapter only has first page

### ISSUE THREAD

**Issue by 2qU24Tlb** [lorenzodifuccia/safaribooks#338] opened 2023-02-19 19:08 UTC
Hi,
I tried to download this (book)[https://www.oreilly.com/library/view/akka-in-action/9781617291012/] today. It seems the download finished successfully and I can see the epub file generated. But when I opened it I can only see the first page in each chapter. Even I tried to download it again, still the same. Can someone please take a look? Thanks.

**Comment by dserodio** [comment] 2023-03-09 20:47
Duplicate of #290

**Closed** 2023-05-05 10:20 UTC
